[2025-08-18T08:44:31.989+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T08:44:32.034+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:38:28.668048+00:00 [queued]>
[2025-08-18T08:44:32.048+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:38:28.668048+00:00 [queued]>
[2025-08-18T08:44:32.049+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-08-18T08:44:32.074+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): ingest_raw> on 2025-08-18 08:38:28.668048+00:00
[2025-08-18T08:44:32.081+0000] {standard_task_runner.py:63} INFO - Started process 189 to run task
[2025-08-18T08:44:32.085+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_exec', 'ingest_raw', 'manual__2025-08-18T08:38:28.668048+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpi_nyuhtn']
[2025-08-18T08:44:32.087+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask ingest_raw
[2025-08-18T08:44:32.151+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:38:28.668048+00:00 [running]> on host 57dc016a750c
[2025-08-18T08:44:32.280+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_exec' AIRFLOW_CTX_TASK_ID='ingest_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T08:38:28.668048+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T08:38:28.668048+00:00'
[2025-08-18T08:44:32.282+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T08:44:32.335+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T08:44:32.335+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec spark-master spark-submit --master spark://spark-master:7077 --deploy-mode client --packages org.apache.spark:spark-avro_2.12:3.5.1 /opt/***/jobs/ingestion/ingest_raw_to_hdfs.py']
[2025-08-18T08:44:32.349+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T08:44:32.370+0000] {subprocess.py:93} INFO - permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/spark-master/json": dial unix /var/run/docker.sock: connect: permission denied
[2025-08-18T08:44:32.372+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T08:44:32.373+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T08:44:32.390+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T08:44:32.395+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=youtube_pipeline_exec, task_id=ingest_raw, execution_date=20250818T083828, start_date=20250818T084432, end_date=20250818T084432
[2025-08-18T08:44:32.420+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task ingest_raw (Bash command failed. The command returned a non-zero exit code 1.; 189)
[2025-08-18T08:44:32.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T08:44:32.499+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T08:44:32.511+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
