[2025-08-18T18:28:18.669+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T18:28:18.715+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.validate_transform manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:28:18.728+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.validate_transform manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:28:18.728+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-08-18T18:28:18.745+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): validate_transform> on 2025-08-18 18:24:04.884207+00:00
[2025-08-18T18:28:18.752+0000] {standard_task_runner.py:63} INFO - Started process 10674 to run task
[2025-08-18T18:28:18.756+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'validate_transform', 'manual__2025-08-18T18:24:04.884207+00:00', '--job-id', '467', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmp13pimcf0']
[2025-08-18T18:28:18.759+0000] {standard_task_runner.py:91} INFO - Job 467: Subtask validate_transform
[2025-08-18T18:28:18.816+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.validate_transform manual__2025-08-18T18:24:04.884207+00:00 [running]> on host 47205959681c
[2025-08-18T18:28:18.923+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='validate_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T18:24:04.884207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T18:24:04.884207+00:00'
[2025-08-18T18:28:18.924+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T18:28:18.942+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T18:28:18.943+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        ROW_COUNT=$(docker exec namenode hdfs dfs -cat /storage/hdfs/processed/golden_dataset/part-* | wc -l)\n        if [ "$ROW_COUNT" -lt 1 ]; then\n            echo "Transform failed: no rows in golden dataset" && exit 1\n        else\n            echo "Transform OK ($ROW_COUNT rows)"\n        fi\n\n        ']
[2025-08-18T18:28:18.955+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T18:28:20.957+0000] {subprocess.py:93} INFO - 2025-08-18 18:28:20,952 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-08-18T18:28:22.956+0000] {subprocess.py:93} INFO - Transform OK (793187 rows)
[2025-08-18T18:28:22.958+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-18T18:28:22.960+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T18:28:23.069+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=youtube_pipeline_batch_data, task_id=validate_transform, execution_date=20250818T182404, start_date=20250818T182818, end_date=20250818T182823
[2025-08-18T18:28:23.194+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-18T18:28:23.251+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-18T18:28:23.252+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
