[2025-08-18T13:42:34.920+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T13:42:34.981+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.check_raw_files manual__2025-08-18T13:41:31.757231+00:00 [queued]>
[2025-08-18T13:42:34.997+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.check_raw_files manual__2025-08-18T13:41:31.757231+00:00 [queued]>
[2025-08-18T13:42:34.998+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2025-08-18T13:42:35.025+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): check_raw_files> on 2025-08-18 13:41:31.757231+00:00
[2025-08-18T13:42:35.032+0000] {standard_task_runner.py:63} INFO - Started process 5264 to run task
[2025-08-18T13:42:35.038+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'check_raw_files', 'manual__2025-08-18T13:41:31.757231+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpz45dfd1b']
[2025-08-18T13:42:35.042+0000] {standard_task_runner.py:91} INFO - Job 337: Subtask check_raw_files
[2025-08-18T13:42:35.130+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.check_raw_files manual__2025-08-18T13:41:31.757231+00:00 [running]> on host 47205959681c
[2025-08-18T13:42:35.309+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='check_raw_files' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T13:41:31.757231+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T13:41:31.757231+00:00'
[2025-08-18T13:42:35.310+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T13:42:35.349+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T13:42:35.351+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        if hdfs dfs -test -e /storage/hdfs/raw/; then\n            echo "Found raw files"\n        else\n            echo "No raw files found, exiting" && exit 1\n        fi\n        ']
[2025-08-18T13:42:35.374+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T13:42:35.378+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 2: hdfs: command not found
[2025-08-18T13:42:35.379+0000] {subprocess.py:93} INFO - No raw files found, exiting
[2025-08-18T13:42:35.382+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T13:42:35.383+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T13:42:35.412+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T13:42:35.422+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=check_raw_files, execution_date=20250818T134131, start_date=20250818T134234, end_date=20250818T134235
[2025-08-18T13:42:35.471+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 337 for task check_raw_files (Bash command failed. The command returned a non-zero exit code 1.; 5264)
[2025-08-18T13:42:35.500+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T13:42:35.615+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T13:42:35.624+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
