[2025-08-19T08:55:21.993+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T08:55:22.036+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.drop_views manual__2025-08-19T08:54:13.416914+00:00 [queued]>
[2025-08-19T08:55:22.050+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.drop_views manual__2025-08-19T08:54:13.416914+00:00 [queued]>
[2025-08-19T08:55:22.050+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2025-08-19T08:55:22.076+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): drop_views> on 2025-08-19 08:54:13.416914+00:00
[2025-08-19T08:55:22.082+0000] {standard_task_runner.py:63} INFO - Started process 2025 to run task
[2025-08-19T08:55:22.086+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'drop_views', 'manual__2025-08-19T08:54:13.416914+00:00', '--job-id', '551', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmp7h7w9sh5']
[2025-08-19T08:55:22.089+0000] {standard_task_runner.py:91} INFO - Job 551: Subtask drop_views
[2025-08-19T08:55:22.145+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.drop_views manual__2025-08-19T08:54:13.416914+00:00 [running]> on host 0121d0ff2e32
[2025-08-19T08:55:22.249+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='drop_views' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T08:54:13.416914+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T08:54:13.416914+00:00'
[2025-08-19T08:55:22.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T08:55:22.269+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-19T08:55:22.270+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec -i youtube-pipeline-project_citus_coordinator_1 psql -U citus -d youtube_dw -c "DROP VIEW IF EXISTS avg_views_comments CASCADE; DROP VIEW IF EXISTS vw_q02_top_engagement_channels CASCADE; DROP VIEW IF EXISTS vw_q03_gold_combinations CASCADE; DROP VIEW IF EXISTS vw_q04_problem_types CASCADE; DROP VIEW IF EXISTS vw_q05_tags_core_metrics CASCADE; DROP VIEW IF EXISTS vw_q06_magic_tags CASCADE; DROP VIEW IF EXISTS vw_q07_speed_to_viral CASCADE; DROP VIEW IF EXISTS vw_q08_desc_thumb_performance CASCADE; DROP VIEW IF EXISTS vw_q09_seasonal_launch CASCADE; DROP VIEW IF EXISTS vw_q10_channel_top_video CASCADE;"']
[2025-08-19T08:55:22.285+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T08:55:22.320+0000] {subprocess.py:93} INFO - Error: No such container: youtube-pipeline-project_citus_coordinator_1
[2025-08-19T08:55:22.325+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-19T08:55:22.326+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T08:55:22.345+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-19T08:55:22.352+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=drop_views, execution_date=20250819T085413, start_date=20250819T085522, end_date=20250819T085522
[2025-08-19T08:55:22.373+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 551 for task drop_views (Bash command failed. The command returned a non-zero exit code 1.; 2025)
[2025-08-19T08:55:22.419+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-19T08:55:22.464+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-19T08:55:22.465+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
