[2025-08-18T08:46:36.807+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T08:46:36.845+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:41:34.717564+00:00 [queued]>
[2025-08-18T08:46:36.855+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:41:34.717564+00:00 [queued]>
[2025-08-18T08:46:36.855+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-08-18T08:46:36.879+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): ingest_raw> on 2025-08-18 08:41:34.717564+00:00
[2025-08-18T08:46:36.885+0000] {standard_task_runner.py:63} INFO - Started process 249 to run task
[2025-08-18T08:46:36.888+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_exec', 'ingest_raw', 'manual__2025-08-18T08:41:34.717564+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpsrahxetz']
[2025-08-18T08:46:36.891+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask ingest_raw
[2025-08-18T08:46:36.945+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_exec.ingest_raw manual__2025-08-18T08:41:34.717564+00:00 [running]> on host 57dc016a750c
[2025-08-18T08:46:37.047+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_exec' AIRFLOW_CTX_TASK_ID='ingest_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T08:41:34.717564+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T08:41:34.717564+00:00'
[2025-08-18T08:46:37.048+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T08:46:37.065+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T08:46:37.066+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec spark-master spark-submit --master spark://spark-master:7077 --deploy-mode client --packages org.apache.spark:spark-avro_2.12:3.5.1 /opt/***/jobs/ingestion/ingest_raw_to_hdfs.py']
[2025-08-18T08:46:37.078+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T08:46:37.096+0000] {subprocess.py:93} INFO - permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/spark-master/json": dial unix /var/run/docker.sock: connect: permission denied
[2025-08-18T08:46:37.097+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T08:46:37.098+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T08:46:37.112+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T08:46:37.116+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=youtube_pipeline_exec, task_id=ingest_raw, execution_date=20250818T084134, start_date=20250818T084636, end_date=20250818T084637
[2025-08-18T08:46:37.142+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task ingest_raw (Bash command failed. The command returned a non-zero exit code 1.; 249)
[2025-08-18T08:46:37.181+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T08:46:37.214+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T08:46:37.225+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
