[2025-08-18T18:30:34.150+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T18:30:34.376+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_09_seasonal_launch manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:30:34.442+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_09_seasonal_launch manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:30:34.442+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-08-18T18:30:34.555+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_q_09_seasonal_launch> on 2025-08-18 18:24:04.884207+00:00
[2025-08-18T18:30:34.570+0000] {standard_task_runner.py:63} INFO - Started process 10735 to run task
[2025-08-18T18:30:34.587+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_09_seasonal_launch', 'manual__2025-08-18T18:24:04.884207+00:00', '--job-id', '472', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmp8u88dqwp']
[2025-08-18T18:30:34.590+0000] {standard_task_runner.py:91} INFO - Job 472: Subtask run_q_09_seasonal_launch
[2025-08-18T18:30:34.873+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_09_seasonal_launch manual__2025-08-18T18:24:04.884207+00:00 [running]> on host 47205959681c
[2025-08-18T18:30:35.518+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='run_q_09_seasonal_launch' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T18:24:04.884207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T18:24:04.884207+00:00'
[2025-08-18T18:30:35.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T18:30:35.640+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T18:30:35.644+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=citus psql -h citus_coordinator-U citus -d youtube_dw -f /opt/***/sql/q_09_seasonal_launch.sql']
[2025-08-18T18:30:35.678+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T18:30:36.055+0000] {subprocess.py:93} INFO - psql: error: could not translate host name "citus_coordinator-U" to address: Temporary failure in name resolution
[2025-08-18T18:30:36.058+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T18:30:36.060+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T18:30:36.196+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T18:30:36.224+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_09_seasonal_launch, execution_date=20250818T182404, start_date=20250818T183034, end_date=20250818T183036
[2025-08-18T18:30:36.294+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 472 for task run_q_09_seasonal_launch (Bash command failed. The command returned a non-zero exit code 2.; 10735)
[2025-08-18T18:30:36.343+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T18:30:36.652+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T18:30:36.653+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
