[2025-08-18T18:31:08.195+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T18:31:08.435+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_02_top_engagement_channels manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:31:08.514+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_02_top_engagement_channels manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:31:08.515+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-08-18T18:31:08.685+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_q_02_top_engagement_channels> on 2025-08-18 18:24:04.884207+00:00
[2025-08-18T18:31:08.783+0000] {standard_task_runner.py:63} INFO - Started process 10769 to run task
[2025-08-18T18:31:08.805+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_02_top_engagement_channels', 'manual__2025-08-18T18:24:04.884207+00:00', '--job-id', '482', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpo3hlzba6']
[2025-08-18T18:31:08.820+0000] {standard_task_runner.py:91} INFO - Job 482: Subtask run_q_02_top_engagement_channels
[2025-08-18T18:31:09.131+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_02_top_engagement_channels manual__2025-08-18T18:24:04.884207+00:00 [running]> on host 47205959681c
[2025-08-18T18:31:09.485+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='run_q_02_top_engagement_channels' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T18:24:04.884207+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T18:24:04.884207+00:00'
[2025-08-18T18:31:09.486+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T18:31:09.572+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T18:31:09.578+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=citus psql -h citus_coordinator-U citus -d youtube_dw -f /opt/***/sql/q_02_top_engagement_channels.sql']
[2025-08-18T18:31:09.620+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T18:31:09.748+0000] {subprocess.py:93} INFO - psql: error: could not translate host name "citus_coordinator-U" to address: Temporary failure in name resolution
[2025-08-18T18:31:09.749+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T18:31:09.757+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T18:31:09.868+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T18:31:09.892+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_02_top_engagement_channels, execution_date=20250818T182404, start_date=20250818T183108, end_date=20250818T183109
[2025-08-18T18:31:09.933+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 482 for task run_q_02_top_engagement_channels (Bash command failed. The command returned a non-zero exit code 2.; 10769)
[2025-08-18T18:31:09.990+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T18:31:10.590+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T18:31:10.604+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
