[2025-08-18T18:30:34.183+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T18:30:34.344+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_10_channel_top_video manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:30:34.406+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_10_channel_top_video manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:30:34.407+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-08-18T18:30:34.481+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_q_10_channel_top_video> on 2025-08-18 18:24:04.884207+00:00
[2025-08-18T18:30:34.493+0000] {standard_task_runner.py:63} INFO - Started process 10731 to run task
[2025-08-18T18:30:34.506+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_10_channel_top_video', 'manual__2025-08-18T18:24:04.884207+00:00', '--job-id', '475', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpq0gnqyn5']
[2025-08-18T18:30:34.510+0000] {standard_task_runner.py:91} INFO - Job 475: Subtask run_q_10_channel_top_video
[2025-08-18T18:30:34.755+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_10_channel_top_video manual__2025-08-18T18:24:04.884207+00:00 [running]> on host 47205959681c
[2025-08-18T18:30:35.495+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='run_q_10_channel_top_video' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T18:24:04.884207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T18:24:04.884207+00:00'
[2025-08-18T18:30:35.496+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T18:30:35.596+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T18:30:35.598+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=citus psql -h citus_coordinator-U citus -d youtube_dw -f /opt/***/sql/q_10_channel_top_video.sql']
[2025-08-18T18:30:35.685+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T18:30:36.052+0000] {subprocess.py:93} INFO - psql: error: could not translate host name "citus_coordinator-U" to address: Temporary failure in name resolution
[2025-08-18T18:30:36.063+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T18:30:36.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T18:30:36.164+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T18:30:36.173+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_10_channel_top_video, execution_date=20250818T182404, start_date=20250818T183034, end_date=20250818T183036
[2025-08-18T18:30:36.433+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 475 for task run_q_10_channel_top_video (Bash command failed. The command returned a non-zero exit code 2.; 10731)
[2025-08-18T18:30:36.471+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T18:30:36.836+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T18:30:36.840+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
