[2025-08-18T13:22:46.119+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T13:22:46.298+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_01_avg_views_comments manual__2025-08-18T13:16:17.589887+00:00 [queued]>
[2025-08-18T13:22:46.403+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_01_avg_views_comments manual__2025-08-18T13:16:17.589887+00:00 [queued]>
[2025-08-18T13:22:46.404+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-08-18T13:22:46.589+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_q_01_avg_views_comments> on 2025-08-18 13:16:17.589887+00:00
[2025-08-18T13:22:46.614+0000] {standard_task_runner.py:63} INFO - Started process 4910 to run task
[2025-08-18T13:22:46.635+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_01_avg_views_comments', 'manual__2025-08-18T13:16:17.589887+00:00', '--job-id', '296', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpdzp6d5uk']
[2025-08-18T13:22:46.639+0000] {standard_task_runner.py:91} INFO - Job 296: Subtask run_q_01_avg_views_comments
[2025-08-18T13:22:46.857+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_01_avg_views_comments manual__2025-08-18T13:16:17.589887+00:00 [running]> on host 47205959681c
[2025-08-18T13:22:47.397+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='run_q_01_avg_views_comments' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T13:16:17.589887+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T13:16:17.589887+00:00'
[2025-08-18T13:22:47.398+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T13:22:47.463+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T13:22:47.469+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=citus psql -h citus_coordinator -U citus -d youtube_dw -f /opt/***/sql/q_01_avg_views_comments']
[2025-08-18T13:22:47.521+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T13:22:47.795+0000] {subprocess.py:93} INFO - psql: error: /opt/***/sql/q_01_avg_views_comments: No such file or directory
[2025-08-18T13:22:47.796+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T13:22:47.798+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T13:22:47.902+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T13:22:47.922+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_01_avg_views_comments, execution_date=20250818T131617, start_date=20250818T132246, end_date=20250818T132247
[2025-08-18T13:22:47.979+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 296 for task run_q_01_avg_views_comments (Bash command failed. The command returned a non-zero exit code 1.; 4910)
[2025-08-18T13:22:48.036+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T13:22:48.111+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T13:22:48.113+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
