[2025-08-18T11:43:35.805+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T11:43:36.004+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_06_magic_tags manual__2025-08-18T11:34:47.904341+00:00 [queued]>
[2025-08-18T11:43:36.093+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_06_magic_tags manual__2025-08-18T11:34:47.904341+00:00 [queued]>
[2025-08-18T11:43:36.096+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-08-18T11:43:36.203+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): run_q_06_magic_tags> on 2025-08-18 11:34:47.904341+00:00
[2025-08-18T11:43:36.226+0000] {standard_task_runner.py:63} INFO - Started process 3194 to run task
[2025-08-18T11:43:36.250+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_06_magic_tags', 'manual__2025-08-18T11:34:47.904341+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpyzn3k7js']
[2025-08-18T11:43:36.258+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask run_q_06_magic_tags
[2025-08-18T11:43:36.670+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_06_magic_tags manual__2025-08-18T11:34:47.904341+00:00 [running]> on host 47205959681c
[2025-08-18T11:43:37.138+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'run_q_06_magic_tags', field 'sql'. Template: '/opt/***/sql/q_06_magic_tags.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/q_06_magic_tags.sql
[2025-08-18T11:43:37.144+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2476, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2629, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3079, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/q_06_magic_tags.sql
[2025-08-18T11:43:37.190+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_06_magic_tags, execution_date=20250818T113447, start_date=20250818T114336, end_date=20250818T114337
[2025-08-18T11:43:37.220+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task run_q_06_magic_tags (/opt/airflow/sql/q_06_magic_tags.sql; 3194)
[2025-08-18T11:43:37.290+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T11:43:37.494+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-08-18T11:43:37.711+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T11:43:37.719+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
