[2025-08-19T09:38:51.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:38:52.239+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.validate_transform manual__2025-08-19T09:11:07.475998+00:00 [queued]>
[2025-08-19T09:38:52.348+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.validate_transform manual__2025-08-19T09:11:07.475998+00:00 [queued]>
[2025-08-19T09:38:52.351+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-08-19T09:38:52.472+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): validate_transform> on 2025-08-19 09:11:07.475998+00:00
[2025-08-19T09:38:52.555+0000] {standard_task_runner.py:63} INFO - Started process 2617 to run task
[2025-08-19T09:38:52.566+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'validate_transform', 'manual__2025-08-19T09:11:07.475998+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpv1bdago2']
[2025-08-19T09:38:52.587+0000] {standard_task_runner.py:91} INFO - Job 615: Subtask validate_transform
[2025-08-19T09:38:53.449+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.validate_transform manual__2025-08-19T09:11:07.475998+00:00 [running]> on host 54bf3a3eaeab
[2025-08-19T09:38:54.590+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='validate_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:11:07.475998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T09:11:07.475998+00:00'
[2025-08-19T09:38:54.592+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:38:54.772+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-19T09:38:54.773+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        ROW_COUNT=$(docker exec namenode hdfs dfs -cat /storage/hdfs/processed/golden_dataset/part-* | wc -l)\n        if [ "$ROW_COUNT" -lt 1 ]; then\n            echo "Transform failed: no rows in golden dataset" && exit 1\n        else\n            echo "Transform OK ($ROW_COUNT rows)"\n        fi\n\n        ']
[2025-08-19T09:38:54.828+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T09:39:15.237+0000] {subprocess.py:93} INFO - 2025-08-19 09:39:15,236 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-08-19T09:39:23.435+0000] {subprocess.py:93} INFO - Transform OK (793187 rows)
[2025-08-19T09:39:23.437+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-19T09:39:23.439+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:39:23.533+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=youtube_pipeline_batch_data, task_id=validate_transform, execution_date=20250819T091107, start_date=20250819T093852, end_date=20250819T093923
[2025-08-19T09:39:23.652+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:39:23.852+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:39:23.871+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
