[2025-08-18T18:31:08.159+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T18:31:08.273+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_03_gold_combinations manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:31:08.321+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_03_gold_combinations manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:31:08.322+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-08-18T18:31:08.371+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_q_03_gold_combinations> on 2025-08-18 18:24:04.884207+00:00
[2025-08-18T18:31:08.386+0000] {standard_task_runner.py:63} INFO - Started process 10765 to run task
[2025-08-18T18:31:08.394+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_03_gold_combinations', 'manual__2025-08-18T18:24:04.884207+00:00', '--job-id', '480', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpoasq7yww']
[2025-08-18T18:31:08.398+0000] {standard_task_runner.py:91} INFO - Job 480: Subtask run_q_03_gold_combinations
[2025-08-18T18:31:08.667+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_03_gold_combinations manual__2025-08-18T18:24:04.884207+00:00 [running]> on host 47205959681c
[2025-08-18T18:31:09.463+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='run_q_03_gold_combinations' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T18:24:04.884207+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T18:24:04.884207+00:00'
[2025-08-18T18:31:09.466+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T18:31:09.501+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T18:31:09.502+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=citus psql -h citus_coordinator-U citus -d youtube_dw -f /opt/***/sql/q_03_gold_combinations.sql']
[2025-08-18T18:31:09.522+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T18:31:09.722+0000] {subprocess.py:93} INFO - psql: error: could not translate host name "citus_coordinator-U" to address: Temporary failure in name resolution
[2025-08-18T18:31:09.723+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T18:31:09.732+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T18:31:09.772+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T18:31:09.782+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_03_gold_combinations, execution_date=20250818T182404, start_date=20250818T183108, end_date=20250818T183109
[2025-08-18T18:31:09.831+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 480 for task run_q_03_gold_combinations (Bash command failed. The command returned a non-zero exit code 2.; 10765)
[2025-08-18T18:31:09.932+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T18:31:10.440+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T18:31:10.453+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
